services:
  - type: web
    name: merkipaki
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: APIFY_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: merkipaki-db
          property: connectionString

databases:
  - name: merkipaki-db
    plan: free
