services:
  - type: web
    name: merkipaki
    env: node
    plan: free
    buildCommand: NPM_CONFIG_BUILD_FROM_SOURCE=sqlite3 npm ci && npm rebuild sqlite3 --build-from-source
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: APIFY_TOKEN
        sync: false
