services:
  - type: web
    name: merkipaki
    env: node
    plan: free
    buildCommand: npm ci --build-from-source=sqlite3
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: APIFY_TOKEN
        sync: false
